[package]
name = "interp"
version = "0.0.1"
authors = ["Felix Stock <felix@stockfamily.at>"]
edition = "2024"
description = "A rudimentary Interpretor for python written in Rust"

[[bin]]
name = "interp"
path = "src/main.rs"

[lib]
name = "interp"
path = "src/main.rs"


[dependencies]
# Lists packages needed to compile and run the package's code
strum = "0.28"
strum_macros = "0.28"


[dev-dependencies]
# Lists packages needed only for tests, examples, and benchmarks

[build-dependencies]
# Lists packages needed by build scripts (build.rs)
# Example: cc = "1.0"
